### ISSUE TITLE
Can't install on Craft 5: No plugin exists with the handle "craft-toolbelt".

### ISSUE THREAD

**Issue by robzor** [zaengle/craft-toolbelt#38]
EDIT: I've got it working by following the instructions in your readme but I think there is something you might need to do for the Plugin Store end :)

Hi there, I'm having a strange issue when trying to install your plugin.

I have a fresh brand new install of Craft 5 and when I try to install your plugin I get the error: 

`*** failed to install craft-toolbelt: No plugin exists with the handle "craft-toolbelt".`

I've tried it both through the plugin store and using the command **(from the Craft CMS plugin store)** `composer require "zaengle/craft-toolbelt:^5.0.6" -w && php craft plugin/install craft-toolbelt` whilst inside the DDEV shell.

![CleanShot 2024-07-25 at 12  52 59](https://github.com/user-attachments/assets/3d2015b9-d20c-4b6b-9d22-8d73dd058a6c)

Additionally, the plugin page says "0 active installs" but I know at least 1 colleague who is using your plugin! :D

**Comment by robzor** [comment]
Ohhhhh, I think it might be because the plugin handle is actually `toolbelt` but the package name is `craft-toolbelt`? 

![CleanShot 2024-07-25 at 12  58 21](https://github.com/user-attachments/assets/677d6c45-bb53-46bd-9bf2-700744332e7f)

**Comment by robzor** [comment]
Hmm, is it because the plugin handle is actually `toolbelt` but the package is `craft-toolbelt`?

If you look at Blitz, for example, the command to install it on the plugin page is `composer require "putyourlightson/craft-blitz:^5.5.1" -w && php craft plugin/install blitz` whereas yours is `craft-toolbelt`

![CleanShot 2024-07-25 at 12  58 21](https://github.com/user-attachments/assets/0a58c8d1-1c41-4c0e-9f26-f3e9029062fd)

**Comment by tomdavies** [comment]
Hi @robzor, thanks for reporting this. As you surmised, it looks like something went awry (or, more likely, I made a boo-boo) when the plugin was submitted to the plugin store, and the handle is listed there incorrectly as `carft-toolbelt` when it should be just plain `toolbelt`. Suspect this explains the broken stats too. I can't edit that field in Craft Console, but I've asked P&T support to fix it, so hopefully this should get resolved soon

**Comment by tomdavies** [comment]
This has been fixed by P&T

**Comment by robzor** [comment]
Hi Tom, sorry I was away on me hols. Thanks for sorting this :)
