### ISSUE TITLE
[Docs] Utility Function > classNames - return value if not true

### ISSUE THREAD

**Issue by austriker27** [zaengle/craft-toolbelt#4]
Based on the viget [classnames docs](https://github.com/vigetlabs/craft-classnames) I think I've determined how to return a value if something is not true. Can you verify this and add it to the docs if true? 

Using `not`:

```twig
<aside {{ attr({
          class: cx({
            'hidden': not opts.displaySidebar,
    })
}) }}
>
```

(Sidenote - I'd love to see more examples of what is possible and what is not so I can use `classNames` better!)

**Comment by tomdavies** [comment]
Feel free to PR the docs!
