### ISSUE TITLE
[Docs] Classnames set default class in a conditional

### ISSUE THREAD

**Issue by austriker27** [zaengle/craft-toolbelt#5]
It wasn't clear to me until I read the viget docs that I would need to add `true` on the right side of a conditional to render the classes as defaults. 

`'col-span-12 lg:col-span-9': true,`

## Example
```twig
<section {{ attr({
          class: cx({
            'col-span-12 lg:col-span-9': true,
            'mx-auto': opts.displaySidebar,
          })
        }) }}
>
```

If this is true, can it be added to docs? Thanks!

**Comment by austriker27** [comment]
Awww, AJ just helped show me the light... Looks like the default classes should go first, like this: 

```twig
      <section {{ attr({
          class: cx('col-span-12 lg:col-span-9', {
            '': not opts.displaySidebar,
            })
        }) }}
      >
```

**Comment by tomdavies** [comment]
@austriker27 the order is not important, just put the non-conditional classnames as one or more string parameters (or arrays if you really want to). You only need to use the object syntax for conditional classes.

In terms of docs I think it's also useful to refer/link to the package we're wrapping: https://github.com/newridetech/php-classnames/ 

We don't add any functionality to that at all. Just expose it to Twig
